### ISSUE TITLE
chicago: fix bill sponsorship by mayor & city clerk

### ISSUE THREAD

**Issue by cathydeng** [opencivicdata/scrapers-us-municipal#93]
here: https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/bills.py#L77-L87

it would make more sense to have rahm as a person who is a member of office of the mayor w/ the post of mayor. reasons:

1. consistency w/ legistar
2. consistency w/ old chicago councilmatic (you can see all the stuff sponsored by rahm)
3. sanity of councilmatic code (much easier to have all bill sponsors be people b/c no need to tweak models/views, minimal changes to data loading)

**Comment by fgregg** [comment]
That may make sense for Rahm, since he has an official relation to the the
city council, and in some sense he is responsible for the legislation
introduced in his name.

But, that argument does not really hold for Susan Mendoza.

And it really doesn't hold for things introduced by a department or agency.
https://chicago.legistar.com/LegislationDetail.aspx?ID=2521561&GUID=7E34353D-DD72-40C0-B8EB-0A08A299A07A&Options=Advanced&Search=

On Fri, Dec 11, 2015 at 3:32 PM, Cathy Deng <notifications@github.com>
wrote:

> here:
> https://github.com/opencivicdata/scrapers-us-municipal/blob/master/chicago/bills.py#L77-L87
>
> it would make more sense to have rahm as a person who is a member of
> office of the mayor w/ the post of mayor. reasons:
>
>    1. consistency w/ legistar
>    2. consistency w/ old chicago councilmatic (you can see all the stuff
>    sponsored by rahm)
>    3. sanity of councilmatic code (much easier to have all bill sponsors
>    be people b/c no need to tweak models/views, minimal changes to data
>    loading)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/93>.
>



-- 
773.888.2718

**Comment by cathydeng** [comment]
ok. what does it mean for something to be sponsored by a dept/agency? is it a specific dept/agency?

**Comment by fgregg** [comment]
I think so, but it's not being captured with sufficient detail by legistar.
Actually, this is something we should just ask Patrick Corcoran.

On Fri, Dec 11, 2015 at 4:14 PM, Cathy Deng <notifications@github.com>
wrote:

> ok. what does it mean for something to be sponsored by a dept/agency? is
> it a specific dept/agency?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opencivicdata/scrapers-us-municipal/issues/93#issuecomment-164063842>
> .
>



-- 
773.888.2718
